### ISSUE TITLE
yottagram does not start

### ISSUE THREAD

**Issue by legacychimera247** [Michal-Szczepaniak/Yottagram#25]
hello, the title says it all i guess, yottagram starts only the first time it has been installed and then does not start anymore

running it from the terminal starts it but can only see the pulley menu and cover says i have 983786287269832649367 unread messages and so on; Other than that, clicking on an option on the pulley results in a crash with a signal 11 error message on the terminal

for the reference i'm on an official xperia xa2, and flashed just yesterday...

**Comment by Matias314** [comment]
Having the same issue on the XA2. It seems to be random. Sometimes I can open and close it a bunch of times (mainly shortly after having booted the phone) and sometimes it only works the first time. When it doesn't work it gives me this message when launched from the terminal: `W] unknown:0 - "Can't lock file \"/home/defaultuser/.local/share/Yottagram/td.binlog\", because it is already in use; check for another program instance running"`

**Comment by Michal-Szczepaniak** [comment]
so just read what that message says. It's already running

**Comment by Matias314** [comment]
How can it be running if it is closed and does not reopen?

**Comment by Michal-Szczepaniak** [comment]
software can be running without having a window and it doesn't reopen because it's already running

just reboot and voila, it won't be already running.

disable daemon mode

**Comment by Matias314** [comment]
Hello, thanks for the suggestion. But unfortunately it did not help, it still breaks in the same way after a while.

**Comment by Michal-Szczepaniak** [comment]
Then don't turn it off , works here
